// AUTO-GENERATED from the official BIR "2307 Jan 2018 ENCS" workbook.
// Page 2 of Form 2307 — Schedules of Alphanumeric Tax Codes, reproduced as the
// two side-by-side columns of the printed form.
//   h = heading line, s = indented sub-line (a condition/bracket),
//   i = ATC for an Individual payee, c = ATC for a Corporation.
export type AtcScheduleRow = { h: string; s: string; i: string; c: string };

export const ATC_SCHEDULE_LEFT: AtcScheduleRow[] = [
  { h: "Professional (Lawyers, CPAs, Engineers, etc.)", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI010", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI011", c: "" },
  { h: "Professional (Lawyers, CPAs, Engineers, etc.)", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC010" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC011" },
  { h: "Professional entertainers such as, but not limited to actors and actresses, singers,", s: "", i: "", c: "" },
  { h: "lyricist, composers, emcees", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI020", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI021", c: "" },
  { h: "Professional entertainers such as, but not limited to actors and actresses, singers,", s: "", i: "", c: "" },
  { h: "lyricists, composers, emcees", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC020" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC021" },
  { h: "Professional athletes including basketball players, pelotaris and jockeys", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI030", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI031", c: "" },
  { h: "Professional athletes including basketball players, pelotaris and jockeys", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC030" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC031" },
  { h: "All directors and producers involved in movies, stage, radio, television and musical", s: "", i: "", c: "" },
  { h: "productions", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI040", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI041", c: "" },
  { h: "All directors and producers involved in movies, stage, radio, television and musical", s: "", i: "", c: "" },
  { h: "productions", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC040" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC041" },
  { h: "Management and technical consultants", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI050", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI051", c: "" },
  { h: "Management and technical consultants", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC050" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC051" },
  { h: "Business and bookkeeping agents and agencies", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI060", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI061", c: "" },
  { h: "Business and bookkeeping agents and agencies", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC060" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC061" },
  { h: "Insurance agents and insurance adjusters", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI070", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI071", c: "" },
  { h: "Insurance agents and insurance adjusters", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC070" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC071" },
  { h: "Other recipients of talent fees", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI080", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI081", c: "" },
  { h: "Other recipients of talent fees", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC080" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC081" },
  { h: "Fees of directors who are not employees of the company", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI090", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI091", c: "" },
  { h: "Rentals: On gross rental or lease for the continued use or possession of personal", s: "", i: "WI100", c: "WC100" },
  { h: "property in excess of Ten thousand pesos (P 10,000) annually and real property", s: "", i: "WI100", c: "WC100" },
  { h: "used in business which the payor or obligor has not taken title or is not taking title,", s: "", i: "WI100", c: "WC100" },
  { h: "or in which has no equity; poles, satellites, transmission facilities and billboards", s: "", i: "WI100", c: "WC100" },
  { h: "Cinematographic film rentals and other payments to resident individuals and", s: "", i: "WI110", c: "WC110" },
  { h: "corporate cinematographic film owners, lessors or distributors", s: "", i: "WI110", c: "WC110" },
  { h: "Income payments to certain contractors", s: "", i: "WI120", c: "WC120" },
  { h: "Income distribution to the beneficiaries of estates and trusts", s: "", i: "WI130", c: "" },
  { h: "Gross commissions or service fees of customs, insurance, stock, immigration and", s: "", i: "", c: "" },
  { h: "commercial brokers, fees of agents of professional entertainers and real estate", s: "", i: "", c: "" },
  { h: "service Practitioners (RESPs), (i.e. real estate consultants, real estate appraisers", s: "", i: "", c: "" },
  { h: "and real estate brokers)", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI139", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI140", c: "" },
  { h: "Gross commissions or service fees of customs, insurance, stock, immigration and", s: "", i: "", c: "" },
  { h: "commercial brokers, fees of agents of professional entertainers and real estate", s: "", i: "", c: "" },
  { h: "service Practitioners (RESPs), (i.e. real estate consultants, real estate appraisers", s: "", i: "", c: "" },
  { h: "and real estate brokers)", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC139" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC140" },
  { h: "Professional fees paid to medical practitioners (includes doctors of medicine,", s: "", i: "", c: "" },
  { h: "doctors of veterinary science & dentists) by hospitals & clinics or paid directly by", s: "", i: "", c: "" },
  { h: "Health Maintenance Organizations (HMOs) and/or similar establishments", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI151", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI150", c: "" },
  { h: "Professional fees paid to medical practitioners (includes doctors of medicine", s: "", i: "", c: "" },
  { h: "doctors of veterinary science & dentists) by hospitals & clinics or paid directly by", s: "", i: "", c: "" },
  { h: "Health Maintenance Organizations (HMOs) and/or similar establishments", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC151" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC150" },
  { h: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only", s: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only", i: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only", c: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only" },
  { h: "Tax on Carriers and Keepers of Garages", s: "", i: "", c: "WB030" },
  { h: "Franchise Tax on Gas and Utilities", s: "", i: "", c: "WB040" },
  { h: "Franchise Tax on radio & radio & TV broadcasting companies whose annual gross receipts do", s: "", i: "", c: "WB050" },
  { h: "not exceed P10M & who are not VAT-registered taxpayers", s: "", i: "", c: "WB050" },
  { h: "Tax on Life Insurance Premiums", s: "", i: "", c: "WB070" },
  { h: "Tax on Overseas Dispatch, Message or Conversation from the Philippines", s: "", i: "", c: "WB090" },
  { h: "Tax on Banks and Non-Bank Financial Intermediaries Performing Quasi Banking Functions", s: "", i: "", c: "" },
  { h: "A. On interest, commissions and discounts from lending activities as well as income from financial", s: "", i: "", c: "" },
  { h: "leasing, on the basis of the remaining maturities of instrument from which such receipt are derived", s: "", i: "", c: "" },
  { h: "-", s: "Maturity period is five years or less", i: "0.05", c: "WB301" },
  { h: "-", s: "Maturity period is more than five years", i: "0.01", c: "WB303" },
  { h: "B. On dividends and equity shares and net income of subsidiaries", s: "", i: "0", c: "WB102" },
  { h: "C. On royalties, rentals of property, real or personal, profits from exchange", s: "", i: "", c: "WB103" },
  { h: "and all other items treated as gross income under the Code", s: "", i: "0.07", c: "WB103" },
  { h: "D. On net trading gains within the taxable year on foreign currency, debt", s: "", i: "", c: "WB104" },
  { h: "securities, derivatives and other similar financial instruments", s: "", i: "0.07", c: "WB104" },
  { h: "Business tax on Agents of Foreign Insurance Companies - Owner of the Property", s: "", i: "", c: "WB121" },
  { h: "Tax on International Carriers", s: "", i: "", c: "WB130" },
  { h: "Business Tax on Agents of Foreign Insurance Companies - Insurance Age", s: "", i: "", c: "WB120" },
  { h: "Business Tax on Agents of Foreign Insurance Companies - Owner of the Property", s: "", i: "", c: "WB121" },
  { h: "Tax on International Carriers", s: "", i: "", c: "WB130" },
];

export const ATC_SCHEDULE_RIGHT: AtcScheduleRow[] = [
  { h: "Payment by the General Professional Partnerships (GPPs) to its partners", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "WI152", c: "" },
  { h: "", s: "If gross income exceeds P 720,000", i: "WI153", c: "" },
  { h: "Income payments made by credit card companies", s: "", i: "WI156", c: "WC156" },
  { h: "Additional income payments to government personnel from importers, shipping", s: "", i: "WI159", c: "" },
  { h: "and airline companies or their agents for overtime services", s: "", i: "WI159", c: "" },
  { h: "Income payments made by the government and government-owned and", s: "", i: "WI640", c: "WC640" },
  { h: "controlled corporations (GOCCs) to its local/resident suppliers of goods", s: "", i: "WI640", c: "WC640" },
  { h: "other than those covered by other rates of withholding tax", s: "", i: "WI640", c: "WC640" },
  { h: "Income payments made by the government and government-owned and", s: "", i: "WI157", c: "WC157" },
  { h: "controlled corporations (GOCCs) to its local/resident suppliers of services", s: "", i: "WI157", c: "WC157" },
  { h: "other than those covered by other rates of withholding tax", s: "", i: "WI157", c: "WC157" },
  { h: "Income payment made by top withholding agents to their local/resident supplier", s: "", i: "WI158", c: "WC158" },
  { h: "of goods other than those covered by other rates of withholding tax", s: "", i: "WI158", c: "WC158" },
  { h: "Income payment made by top withholding agents to their local/resident supplier", s: "", i: "WI160", c: "WC160" },
  { h: "of services other than those covered by other rates of withholding tax", s: "", i: "WI160", c: "WC160" },
  { h: "Commissions, rebates, discounts and other similar considerations paid/granted to", s: "", i: "", c: "" },
  { h: "independent and/or exclusive sales representatives and marketing agents and sub-", s: "", i: "", c: "" },
  { h: "agents of companies, including multi-level marketing companies", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 3M", i: "WI515", c: "" },
  { h: "", s: "If gross income is more than P 3M or VAT Registered regardless of amount", i: "WI516", c: "" },
  { h: "Commissions, rebates, discounts and other similar considerations paid/ granted", s: "", i: "", c: "" },
  { h: "to independent and/or exclusive sales representatives and marketing agents", s: "", i: "", c: "" },
  { h: "and sub-agents of companies, including multi-level marketing companies", s: "", i: "", c: "" },
  { h: "", s: "If gross income for the current year did not exceed P 720,000", i: "", c: "WC515" },
  { h: "", s: "If gross income exceeds P 720,000", i: "", c: "WC516" },
  { h: "Gross payments to embalmers by funeral parlors", s: "", i: "WI530", c: "" },
  { h: "Payments made by pre-need companies to funeral parlors", s: "", i: "WI535", c: "WC535" },
  { h: "Tolling fees paid to refineries", s: "", i: "WI540", c: "WC540" },
  { h: "Income payments made to suppliers of agricultural products in excess", s: "", i: "WI610", c: "WC610" },
  { h: "of cumulative amount of P 300,000 within the same taxable year", s: "", i: "WI610", c: "WC610" },
  { h: "Income payments on purchases of minerals, mineral products and quarry", s: "", i: "WI630", c: "WC630" },
  { h: "such as but not limited to silver, gold, marble, granite, gravel, sand, boulders", s: "", i: "WI630", c: "WC630" },
  { h: "and other mineral products except purchases by Bangko Sentral ng Pilipinas", s: "", i: "WI630", c: "WC630" },
  { h: "Income payments on purchases of minerals, mineral products and quarry", s: "", i: "WI632", c: "WC632" },
  { h: "resources by Bangko Sentral ng Pilipinas (BSP) from gold miners/suppliers under", s: "", i: "WI632", c: "WC632" },
  { h: "PD 1899, as amended by RA No. 7076", s: "", i: "WI632", c: "WC632" },
  { h: "On gross amount of refund given by MERALCO to customers with", s: "", i: "WI650", c: "WC650" },
  { h: "active contracts as classified by MERALCO", s: "", i: "WI650", c: "WC650" },
  { h: "On gross amount of refund given by MERALCO to customers with", s: "", i: "WI651", c: "WC651" },
  { h: "terminated contracts as classified by MERALCO", s: "", i: "WI651", c: "WC651" },
  { h: "On gross amount of interest on the refund of meter deposit whether paid directly to", s: "", i: "WI660", c: "WC660" },
  { h: "the customers or applied against customer’s billings of Residential and General", s: "", i: "WI660", c: "WC660" },
  { h: "Service customers whose monthly electricity consumption exceeds 200 kwh as", s: "", i: "WI660", c: "WC660" },
  { h: "classified by MERALCO", s: "", i: "WI660", c: "WC660" },
  { h: "On gross amount of interest on the refund of meter deposit whether paid directly to", s: "", i: "WI661", c: "WC661" },
  { h: "the customers or applied against customer’s billings of Non- Residential customers", s: "", i: "WI661", c: "WC661" },
  { h: "whose monthly electricity consumption exceeds 200 kwh as classified by", s: "", i: "WI661", c: "WC661" },
  { h: "MERALCO", s: "", i: "WI661", c: "WC661" },
  { h: "On gross amount of interest on the refund of meter deposit whether paid directly to", s: "", i: "WI662", c: "WC662" },
  { h: "the customers or applied against customer’s billings of Residential and General", s: "", i: "WI662", c: "WC662" },
  { h: "Service customers whose monthly electricity consumption exceeds 200 kwh as", s: "", i: "WI662", c: "WC662" },
  { h: "classified by other electric Distribution Utilities (DU)", s: "", i: "WI662", c: "WC662" },
  { h: "On gross amount of interest on the refund of meter deposit whether paid directly to", s: "", i: "WI663", c: "WC663" },
  { h: "the customers or applied against customer’s billings of Non-Residential customers", s: "", i: "WI663", c: "WC663" },
  { h: "whose monthly electricity consumption exceeds 200 kwh as classified by other", s: "", i: "WI663", c: "WC663" },
  { h: "electric Distribution Utilities (DU)", s: "", i: "WI663", c: "WC663" },
  { h: "Income payments made by political parties and candidates of local and national", s: "", i: "WI680", c: "WC680" },
  { h: "elections on all their purchases of goods and services related to campaign", s: "", i: "WI680", c: "WC680" },
  { h: "expenditures, and income payments made by individuals or juridical persons for", s: "", i: "WI680", c: "WC680" },
  { h: "their purchases of goods and services intended to be given as campaign", s: "", i: "WI680", c: "WC680" },
  { h: "contributions to political parties and candidates", s: "", i: "WI680", c: "WC680" },
  { h: "Income payments received by Real Estate Investment Trust (REIT)", s: "", i: "", c: "WC690" },
  { h: "Interest income derived from any other debt instruments not within the", s: "", i: "WI710", c: "WC710" },
  { h: "coverage of deposit substitutes and Revenue Regulations No. 14-2012", s: "", i: "WI710", c: "WC710" },
  { h: "Income payments on locally produced raw sugar", s: "", i: "WI720", c: "WC720" },
  { h: "Sale of Real Property (Ordinary Asset)", s: "", i: "WI555", c: "WC555" },
  { h: "", s: "", i: "WI556", c: "WC556" },
  { h: "", s: "", i: "WI557", c: "WC557" },
  { h: "", s: "", i: "WI558", c: "WC558" },
  { h: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)", s: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)", i: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)", c: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)" },
  { h: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)", s: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)", i: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)", c: "B Money Payments Subject to Withholding of Business Tax by Government or Private Payor (Individual & Corporate)" },
  { h: "Persons Exempt from VAT under Sec. 109BB (creditable)-Government Withholding", s: "", i: "WB080", c: "WB080" },
  { h: "Agent", s: "", i: "WB080", c: "WB080" },
  { h: "Persons Exempt from VAT under Sec. 109BB (creditable)-Private Withholding", s: "", i: "WB082", c: "WB082" },
  { h: "Agent", s: "", i: "WB082", c: "WB082" },
  { h: "VAT Withholding on Purchases of Goods (with waiver of privilege to claim input tax", s: "", i: "WV012", c: "WV012" },
  { h: "credit) (creditable)", s: "", i: "WV012", c: "WV012" },
  { h: "VAT Withholding on Purchases of Services (with waiver of privilege to claim input", s: "", i: "WV022", c: "WV022" },
  { h: "tax credit) (creditable)", s: "", i: "WV022", c: "WV022" },
  { h: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only", s: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only", i: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only", c: "C Money Payments Subject to Withholding of Business Tax by Government Payor Only" },
  { h: "Tax on Other Non-Banks Financial Intermediaries not Performing Quasi-Banking", s: "", i: "", c: "" },
  { h: "Functions", s: "", i: "", c: "" },
  { h: "A.", s: "On interest, commissions and discounts from lending activities as well as Income", i: "", c: "" },
  { h: "from financial leasing, on the basis of the remaining maturities of instrument from", s: "", i: "", c: "" },
  { h: "which such receipt are derived", s: "", i: "", c: "" },
  { h: "-", s: "Maturity period is five years or less", i: "", c: "WB108" },
  { h: "-", s: "Maturity period is more than five years", i: "", c: "WB109" },
  { h: "B.", s: "On all other items treated as gross income under the code", i: "", c: "WB110" },
  { h: "Tax on Cockpits", s: "", i: "", c: "WB140" },
  { h: "Tax on amusement places, such as cabarets, night and day clubs, videoke bars, karaoke bars,", s: "", i: "", c: "WB150" },
  { h: "karaoke television, karaoke boxes, music lounges and other similar establishments", s: "", i: "", c: "WB150" },
  { h: "Tax on Boxing exhibitions", s: "", i: "", c: "WB160" },
  { h: "Tax on Professional basketball games", s: "", i: "", c: "WB170" },
  { h: "Tax on jai-alai and race tracks", s: "", i: "", c: "WB180" },
  { h: "Tax on sale, barter or exchange of stocks listed and traded through Local Stock exchange", s: "", i: "", c: "WB200" },
  { h: "Tax on shares of stock sold or exchanged through initial and secondary public offering", s: "", i: "", c: "" },
  { h: "-", s: "Not over 25%", i: "", c: "WB201" },
  { h: "-", s: "Over 25% but not exceeding 33 1/3%", i: "", c: "WB202" },
  { h: "-", s: "Over 33 1/3%", i: "", c: "WB203" },
];
